version: 2

sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        tags: ["log_this_test"] 
        columns:
          - name: id
            tests:
              - dbt_expectations.expect_column_distinct_count_to_be_greater_than:
                  value: 50
              - not_null
          - name: first_name
            tests:
              - not_null 

      - name: orders
        tags: ["log_this_test"]  
